name: Lint ROS2 package
on:
  # Run this action whenever a pull request is made
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  # Note that we pass each job a different name to distinguish each linter job
  ament_lint_cpp:
    name: ament_${{ matrix.linter }}
#    runs-on: ubuntu-18.04
    runs-on: [ self-hosted ]
    strategy:
      fail-fast: false
      matrix:
        linter: [cppcheck, cpplint, uncrustify, xmllint]
    steps:
      - uses: ros-tooling/setup-ros@v0.1
      - uses: ros-tooling/action-ros-ci@v0.1
        with:
          package-name: my_package
          target-ros2-distro: foxy
          colcon-mixin-name: coverage-gcc
          # If possible, pin the repository in the workflow to a specific commit to avoid
          # changes in colcon-mixin-repository from breaking your tests.
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/5c45b95018788deff62202aaa831ad4c20ebe2c6/index.yaml
