name: Lint ROS2 package
on:
  # Run this action whenever a pull request is made
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  # Note that we pass each job a different name to distinguish each linter job
  ament_lint_cpp:
    name: ament_${{ matrix.linter }}
#    runs-on: ubuntu-18.04
    runs-on: [ self-hosted ]
    strategy:
      fail-fast: false
      matrix:
        linter: [cppcheck, cpplint, uncrustify, xmllint]
　　steps:
      - uses: ros-tooling/setup-ros@v0.1
      - uses: ros-tooling/action-ros-ci@v0.1
        with:
          colcon-mixin-name: asan
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/3e627e0fa30db85aea05a50e2c61a9832664d236/index.yaml
          package-name: my_package
          target-ros2-distro: foxy
